name: aureviarooms
description: A hotel and room management application

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^5.4.4
  connectivity_plus: ^6.1.4
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.0.0
  retry: ^3.1.2
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.11.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^14.0.2
  google_maps_flutter_android: ^2.17.0
  freezed_annotation: ^2.4.1 # O la versión más reciente
  json_annotation: ^4.9.0    # O la versión más reciente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11 # O la versión más reciente
  freezed: ^2.5.2        # O la versión más reciente
  json_serializable: ^6.8.0 # O la versión más reciente

flutter:
  uses-material-design: true
  assets:
    - assets/Logo_Nombre.png
    - .env
