name: aureviarooms
description: A hotel and room management application

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.1.1
  connectivity_plus: ^4.0.2
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.0.0
  retry: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logo_Nombre.png  
    - .env
